export const MAIN_RPC_CONTRACT_NAME = "main";
export const MAIN_RPC_EVENT_FAMILY = "events";

export const MAIN_METHOD_TABLE = {
  openExternal: { args: "object" },
  submitFeedback: { args: "object" },
  getDesktopEnvironment: { args: "none" },
  getWindowState: { args: "none" },
  minimizeWindow: { args: "none" },
  toggleMaximizeWindow: { args: "none" },
  closeWindow: { args: "none" },
  resizeWindowWidth: { args: "object" },
  setTitleBarOverlayTone: { args: "object" },
  getThemeState: { args: "none" },
  setThemePreference: { args: "object" },
  getEgressTunnelEnabled: { args: "none" },
  setEgressTunnelEnabled: { args: "object" },
  getEgressTunnelStatus: { args: "none" },
  getWebauthnProxyEnabled: { args: "none" },
  setWebauthnProxyEnabled: { args: "object" },
  getUpdateStatus: { args: "none" },
  checkForUpdates: { args: "none" },
  setUpdateTrack: { args: "object" },
  quitAndInstallUpdate: { args: "none" },
  setAutoUpdateWhenIdleOptIn: { args: "object" },
  getBoxMigrationStatus: { args: "none" },
  markDeepLinksReady: { args: "none" },
  getOnboardingSeen: { args: "none" },
  setOnboardingSeen: { args: "object" },
  getTimeZone: { args: "none" },
  setTimeZoneOverride: { args: "object" },
  getAutoReviewInstructions: { args: "none" },
  setAutoReviewInstructions: { args: "object" },
  getLocalToolPermission: { args: "none" },
  getLocalToolPermissionCeiling: { args: "none" },
  setLocalToolPermission: { args: "object" },
  recordLocalToolApproval: { args: "object" },
  clearLocalToolApprovals: { args: "none" },
  getSidebarCollapsed: { args: "none" },
  setSidebarCollapsed: { args: "object" },
  pickAvatarSource: { args: "none" },
  pickAvatarFile: { args: "none" },
  generateAgentAvatarImage: { args: "object" },
  resolveAttachmentMedia: { args: "object" },
  readAttachmentText: { args: "object" },
  readAttachmentBytes: { args: "object" },
  stageAttachmentBytes: { args: "object" },
  downloadAttachment: { args: "object" },
  commitStagedAttachments: { args: "object" },
  discardStagedAttachment: { args: "object" },
  forceRecreateComputer: { args: "none" },
  updateComputer: { args: "object" },
  forceReconnectGateway: { args: "none" },
  getExperimentsSnapshot: { args: "none" },
  applyFeatureFlagOverride: { args: "object" },
  refreshFeatureFlags: { args: "none" },
  startRpcTraceWindow: { args: "none" },
  getAgentDefaultModel: { args: "none" },
  setAgentDefaultModel: { args: "object" },
  getComputerUseModel: { args: "none" },
  setComputerUseModel: { args: "object" },
  getHostPinnedAgents: { args: "none" },
  setHostPinnedAgents: { args: "object" },
  getHostSidebarSections: { args: "none" },
  setHostSidebarSections: { args: "object" },
  getAvailableModels: { args: "none" },
  getInferenceRouter: { args: "none" },
  setInferenceRouter: { args: "object" },
  getBoxRuntime: { args: "none" },
  setBoxRuntime: { args: "object" },
  // Required for this method to work at all. bridgeRpcEdge (rpc-edge-runtime.ts:68-72) only
  // creates wrapper functions for keys present in this table, and serveEdge
  // (generated/main-rpc.ts:72) only registers ipcMain.handle for keys in this table. Without
  // the entry the preload wrapper exists but throws a TypeError when called, and the renderer's
  // catch reports "network-error" rather than "unsupported" — so the hardcoded fallback model
  // list then hides the break completely. serveEdge's check (generated/main-rpc.ts:73-84) is
  // one-way: every table method must have a handler, but a handler missing from the table is
  // silently never served.
  listInferenceRouterModels: { args: "object" },
  transcribeAudio: { args: "object" },
  getCursorAuthStatus: { args: "none" },
  loginCursor: { args: "none" },
  cancelCursorLogin: { args: "none" },
  logoutCursor: { args: "none" },
  updateCursorAccountName: { args: "object" },
  getCursorAvatar: { args: "none" },
  getCursorWeeklyUsage: { args: "none" },
  getCursorUsageSummary: { args: "none" },
  getCursorPrReviewPreferences: { args: "none" },
  getCursorPrivacyModeEnabled: { args: "none" },
  getSandAccess: { args: "none" },
  getSandAccessFresh: { args: "none" },
  invokeCursorDashboardAction: { args: "object" },
  cancelCursorSandTrial: { args: "none" },
  reportAgentLoad: { args: "object" },
  reportAccessBlocked: { args: "object" },
  reportAgentsUnreachable: { args: "object" },
  reportRecoveryAction: { args: "object" },
  reportRebuildLifecycle: { args: "object" },
  reportReconciliation: { args: "object" },
  reportBoxVisibility: { args: "object" },
  reportSendLatency: { args: "object" },
  reportSendAck: { args: "object" },
  reportReactionAck: { args: "object" },
  reportRenderTtfr: { args: "object" },
  reportRenderStream: { args: "object" },
  reportVncSession: { args: "object" },
  reportVncLiveness: { args: "object" },
  reportOpenComputer: { args: "object" },
  reportUpdatePrompt: { args: "object" },
  reportSigninGate: { args: "object" },
  reportOnboardingStep: { args: "object" },
  reportClientFailure: { args: "object" },
  openCloudAgent: { args: "object" },
  getLinkMetadata: { args: "object" },
  listSecrets: { args: "none" },
  revealSecret: { args: "object" },
  upsertSecrets: { args: "object" },
  removeSecrets: { args: "object" },
  getMcpState: { args: "none" },
  getEffectivePlugins: { args: "none" },
  getMcpCatalog: { args: "none" },
  getMcpTeamPopularity: { args: "none" },
  getMcpPluginLogo: { args: "object" },
  installEntry: { args: "object" },
  updatePluginInstall: { args: "object" },
  removeMcpServer: { args: "object" },
  uninstallPlugin: { args: "object" },
  authenticateMcpServer: { args: "object" },
  renameMcpAccount: { args: "object" },
  removeMcpAccount: { args: "object" },
  setMcpCustomInstructions: { args: "object" },
  listMcpServerTools: { args: "object" },
  toggleMcpToolDisabled: { args: "object" },
} as const;

export type MainMethod = keyof typeof MAIN_METHOD_TABLE;

export function isMainMethod(name: string): name is MainMethod {
  return Object.hasOwn(MAIN_METHOD_TABLE, name);
}
