import { execFileSync } from "node:child_process";
import { closeSync, mkdirSync, openSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { findSystemErrno } from "../shared/system-errno.js";
import { getHostLockPath } from "./host-paths.js";
export const DEFAULT_TAKEOVER_TIMEOUT_MS = 3_000; export const DEFAULT_POLL_INTERVAL_MS = 100; export const MAX_ACQUIRE_ATTEMPTS = 5;
export function defaultIsProcessAlive(pid: number): boolean { try { process.kill(pid, 0); return true; } catch { return false; } }
export function readProcessCommand(pid: number, platform = process.platform): string | null { if (!Number.isInteger(pid) || pid <= 0) return null; if (platform === "win32") { // Neither `/proc` nor `ps` exists on Windows, so the POSIX-only probe below always returned null here. `probeLegacyHost` (startup-data-root-migration.ts:138-139) treats a THROWN probe as "unknown" but a returned `false` as "absent" вЂ” and "absent" makes `settleStartupDataRoot` rename the data root out from under a live host. A null result must therefore never be produced by an unsupported platform. wmic is absent on current Windows builds, so use CIM; the 5 s timeout keeps a wedged provider from stalling startup.
  try { return execFileSync("powershell.exe", ["-NoProfile", "-NonInteractive", "-Command", `(Get-CimInstance Win32_Process -Filter 'ProcessId = ${pid}').CommandLine`], { encoding: "utf8", timeout: 5_000 }).trim(); } catch { throw new Error(`Cannot determine the command line of pid ${pid} on this platform`); } // A live SYSTEM or elevated process answers with EMPTY stdout and exit code 0 вЂ” measured on spoolsv and dwm. `.trim() || null` turned that into a silent `false`, and `probeLegacyHost` maps a returned `false` to the UNSAFE "absent" (it renames the data root out from under a live host) while mapping a THROW to the safe "unknown". So an empty answer must throw too: we cannot tell "not our host" from "cannot read".
 }
  try { const value = readFileSync(`/proc/${pid}/cmdline`, "utf8"); if (value.length > 0) return value.replace(/\0/g, " ").trim(); } catch {} try { return execFileSync("ps", ["-p", String(pid), "-o", "command="], { encoding: "utf8", timeout: 2_000 }).trim(); } catch { return null; } }
export function isSandHostProcess(pid: number): boolean { return readProcessCommand(pid)?.includes("host-main") === true; }
export function readLockPid(path: string): number | null { try { const pid = Number.parseInt(readFileSync(path, "utf8").trim(), 10); return Number.isInteger(pid) && pid > 0 ? pid : null; } catch { return null; } }
function removeLock(path: string): void { try { unlinkSync(path); } catch {} }
function tryCreateLock(path: string, pid: number): boolean { try { const fd = openSync(path, "wx"); try { writeFileSync(fd, String(pid), "utf8"); } finally { closeSync(fd); } return true; } catch (error) { if (findSystemErrno(error) === "EEXIST") return false; throw error; } }
function makeHandle(path: string, pid: number) { return { path, pid, release() { if (readLockPid(path) === pid) removeLock(path); } }; }
async function waitForExit(pid: number, isAlive: (pid: number) => boolean, delay: (ms: number) => Promise<void>, timeoutMs: number, pollMs: number): Promise<void> { const deadline = Date.now() + timeoutMs; while (isAlive(pid) && Date.now() < deadline) await delay(pollMs); }
export async function acquireHostLock(options: { path?: string; pid?: number; isProcessAlive?: (pid: number) => boolean; isSandHostProcess?: (pid: number) => boolean; terminateProcess?: (pid: number, signal: NodeJS.Signals) => void; delay?: (ms: number) => Promise<void>; takeoverTimeoutMs?: number; pollIntervalMs?: number } = {}) {
  const path = options.path ?? getHostLockPath(); const pid = options.pid ?? process.pid; const isAlive = options.isProcessAlive ?? defaultIsProcessAlive; const hostCheck = options.isSandHostProcess ?? isSandHostProcess; const terminate = options.terminateProcess ?? ((target, signal) => { try { process.kill(target, signal); } catch {} }); const delay = options.delay ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms))); const timeout = options.takeoverTimeoutMs ?? DEFAULT_TAKEOVER_TIMEOUT_MS; const poll = options.pollIntervalMs ?? DEFAULT_POLL_INTERVAL_MS;
  mkdirSync(dirname(path), { recursive: true }); let outcome: "created" | "reclaimed-dead" | "reclaimed-foreign" | "took-over" = "created"; let previousPid: number | undefined;
// hostCheck throws when it cannot determine the command line. main.ts awaits acquireHostLock() OUTSIDE its try/catch, so an escaping throw would kill the host with no reportProcessCrash and no log. Treat "cannot tell" as "keep the existing degraded behaviour" rather than as a crash.
  for (let attempt = 0; attempt < MAX_ACQUIRE_ATTEMPTS; attempt += 1) { if (tryCreateLock(path, pid)) return { outcome, lock: makeHandle(path, pid), ...(previousPid === undefined ? {} : { previousPid }) }; const holder = readLockPid(path); if (holder == null) { outcome = "reclaimed-dead"; removeLock(path); continue; } if (holder === pid) { removeLock(path); continue; } if (!isAlive(holder)) { outcome = "reclaimed-dead"; previousPid = holder; removeLock(path); continue; } if (!hostCheck(holder)) { outcome = "reclaimed-foreign"; previousPid = holder; removeLock(path); continue; } outcome = "took-over"; previousPid = holder; terminate(holder, "SIGTERM"); await waitForExit(holder, isAlive, delay, timeout, poll); if (isAlive(holder)) { terminate(holder, "SIGKILL"); await waitForExit(holder, isAlive, delay, timeout, poll); } removeLock(path); }
  writeFileSync(path, String(pid), "utf8"); return { outcome, lock: makeHandle(path, pid), ...(previousPid === undefined ? {} : { previousPid }) };
}
